# Generated by Django 5.1.1 on 2024-09-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_resultado_delete_minhaopcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Projeto')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do Projeto')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_nome', to='App.nome', verbose_name='Área')),
            ],
        ),
    ]
