# Generated by Django 5.1.1 on 2024-09-04 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_portfolio_opcoes_portfolio_variavel1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='variavel1',
            new_name='css',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='variavel2',
            new_name='java',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='variavel3',
            new_name='python',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='nome',
            field=models.ForeignKey(help_text='Escolha uma tecnologia correspondente.', on_delete=django.db.models.deletion.PROTECT, related_name='app_nome', to='App.nome', verbose_name='Área'),
        ),
    ]
