# Generated by Django 5.1.1 on 2024-09-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_rename_variavel1_portfolio_css_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='css',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='java',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='python',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
