# Generated by Django 5.1.1 on 2024-09-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_portfolio_css_alter_portfolio_java_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='c',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='html',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='javascript',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
