# Generated by Django 5.1.1 on 2024-09-05 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_portfolio_c_portfolio_html_portfolio_javascript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='nome',
            field=models.ForeignKey(blank=True, help_text='Escolha uma tecnologia correspondente.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_nome', to='App.nome', verbose_name='Área'),
        ),
    ]
