# Generated by Django 5.1.1 on 2024-09-09 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_portfolio_descricao_alter_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='descricao',
            field=models.CharField(blank=True, help_text='Maximo de caracteres são 500', max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='app_nome', to='App.nome', verbose_name='Área'),
        ),
    ]
